runtime: nodejs16  # Chọn phiên bản Node.js (ví dụ: nodejs16)

env: standard  # Sử dụng môi trường chuẩn của App Engine

env_variables:
  MY_ENV_VAR: "some_value"  # Thêm biến môi trường nếu cần

automatic_scaling:
  min_instances: 1  # Số lượng instance tối thiểu
  max_instances: 10  # Số lượng instance tối đa
